# This is a basic workflow to help you get started with Actions
name: Prod Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push to the prod branch.
  push:
    branches: [ prod ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  RGName: prod-bicep-demo
  Region: CentralUS
  Environment: prod

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  EnvironmentDeploy:
    runs-on: ubuntu-latest
    environment:
      name: Prod Environment
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login via Az module
        uses: azure/login@v1
        with:
            creds: ${{secrets.AZURE_CREDENTIALS}}
            enable-AzPSSession: true

      - name: Prod_Subscription
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            ./release/Deploy.ps1 -RGName $env:RGName -Region $env:Region -Environment $env:Environment
          azPSVersion: latest